# Generated by Django 5.1.7 on 2025-04-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hr3', 'HR Level 3'), ('hr2', 'HR Level 2'), ('hr1', 'HR Level 1'), ('admin', 'Admin')], default='staff', max_length=10),
        ),
    ]
