# Generated by Django 5.1.7 on 2025-04-03 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_push_time', models.DateTimeField(blank=True, null=True)),
                ('push_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pushed', 'Pushed'), ('revoked', 'Revoked')], default='draft', max_length=10)),
                ('creator', models.ForeignKey(db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
