# Generated by Django 5.1.7 on 2025-04-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='push_status',
            new_name='status',
        ),
    ]
