# Generated by Django 5.1.7 on 2025-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_push_status_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
