# Generated by Django 5.1.7 on 2025-04-04 11:10

import django.db.models.deletion
import myapp.models.profile
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_events_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default/default_avatar.png', null=True, upload_to=myapp.models.profile.user_avatar_path)),
                ('user', models.OneToOneField(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
        ),
    ]
