# Generated by Django 5.1.7 on 2025-04-04 16:14

import myapp.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to=myapp.models.profile.user_avatar_path),
        ),
    ]
