# Generated by Django 5.1.7 on 2025-04-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_eventcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventcomment',
            new_name='event_comme_event_i_72cbde_idx',
            old_name='myapp_event_event_i_0c297e_idx',
        ),
        migrations.RenameIndex(
            model_name='eventcomment',
            new_name='event_comme_author__6e38a1_idx',
            old_name='myapp_event_author__003445_idx',
        ),
        migrations.AlterModelTable(
            name='eventcomment',
            table='event_comment',
        ),
    ]
