# Generated by Django 5.1.7 on 2025-04-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_customuser_groups_customuser_user_permissions'),
        ('myapp', '0021_create_superuser_fixed'),
    ]

    operations = [
    ]
