# Generated by Django 5.1.7 on 2025-04-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_merge_20250406_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
